/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   api-headers-editor.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../api-view-model-transformer/api-view-model-transformer.d.ts" />
/// <reference path="../api-headers-form/api-headers-form.d.ts" />
/// <reference path="../code-mirror/code-mirror.d.ts" />
/// <reference path="../code-mirror-hint/code-mirror-hint.d.ts" />
/// <reference path="../code-mirror-hint/headers-addon.d.ts" />
/// <reference path="../code-mirror-hint/hint-http-headers.d.ts" />
/// <reference path="../arc-icons/arc-icons.d.ts" />
/// <reference path="../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../paper-tooltip/paper-tooltip.d.ts" />
/// <reference path="../headers-parser-behavior/headers-parser-behavior.d.ts" />
/// <reference path="../events-target-behavior/events-target-behavior.d.ts" />
/// <reference path="../clipboard-copy/clipboard-copy.d.ts" />

declare namespace ApiElements {

  /**
   * `api-headers-editor`
   * An element to render headers edior based on AMF data model.
   *
   * By default it renders headers form. The user has an option to switch to
   * source editing mode. `code-mirror` element is used in the later case.
   *
   * ## AMF data model
   *
   * This element renders pre-configured form of headers based on
   * [AMF's](https://github.com/mulesoft/amf) json/ld data model.
   * From the model select `http://raml.org/vocabularies/http#header`
   * node which contains list of headers defined for current object
   * (it can be method, trait, security scheme etc).
   * The model is resolved to internal data model by `api-view-model-transformer`
   * element.
   *
   * ### Example
   *
   * ```html
   * <api-headers-editor id="editor"></api-headers-editor>
   * <script>
   * let data = await getAmfModel();
   * data = data[0]['http://raml.org/vocabularies/document#encodes'][0];
   * data = data['http://raml.org/vocabularies/http#endpoint'][0];
   * data = data['http://www.w3.org/ns/hydra/core#supportedOperation'][0];
   * data = data['http://www.w3.org/ns/hydra/core#expects'][0];
   * data = data['http://raml.org/vocabularies/http#header'];
   * (first endpoint, first method, headers array)
   * editor.amfModel = data;
   * editor.addEventListener('value-changed', (e) => console.log(e.detail.value));
   * < /script>
   * ```
   */
  class ApiHeadersEditor extends
    ArcBehaviors.HeadersParserBehavior(
    ArcBehaviors.EventsTargetBehavior(
    Polymer.Element)) {
    amfHeaders: any[]|null|undefined;

    /**
     * Headers value.
     */
    value: string|null|undefined;

    /**
     * Generated view model fore the headers from `amfModel`.
     * This is automatically set when `amfModel` is set.
     */
    viewModel: any[]|null|undefined;

    /**
     * Value of a Content-Type header.
     * When this value change then editor update the value for the content type. However,
     * to change a single header value, please, use `request-headers-changed` event with `name`
     * and `value` properties set on the detail object.
     */
    contentType: Stirng|null;

    /**
     * If set it will renders the view in the narrow layout.
     */
    narrow: boolean|null|undefined;

    /**
     * When set to true then the source edit mode is enabled
     */
    sourceMode: boolean|null|undefined;

    /**
     * If set, custom headers won't be available in form mode.
     */
    disallowCustom: boolean|null|undefined;

    /**
     * Events target for tranformer
     */
    _transformerTarget: object|null|undefined;

    /**
     * Regexp to search for content type value
     */
    _contentTypeRe: object|null|undefined;
    _attachListeners(node: any): void;
    _detachListeners(node: any): void;

    /**
     * Sets up editor when ready to manipulate DOM.
     */
    ready(): void;

    /**
     * Creates a form editor and places it in the local DOM.
     * This does nothing if the element hasn't been yet initialized
     */
    createForm(): void;

    /**
     * Searches the DOM for the form editor.
     *
     * @returns Editor or undefined if not set.
     */
    formEditor(): ApiHeadersEditor|null|undefined;

    /**
     * Removes references to the form editor.
     * It removes event listeners and removes the form editor from local DOM.
     */
    removeForm(): void;

    /**
     * Updates model data on form element.
     *
     * @param model New model
     */
    _updateFormModel(model: any[]|null): void;

    /**
     * Updates form editor `narrow` property.
     *
     * @param narrow New value
     */
    _updateFormNarrow(narrow: Boolean|null): void;

    /**
     * Creates a code mirror editor and places it in the local DOM.
     * This does nothing if the element hasn't been yet initialized
     */
    createCodeMirror(): void;

    /**
     * Searches the DOM for the CodeMirror editor.
     *
     * @returns Editor or undefined if not set.
     */
    codeMirror(): CodeMirrorElement|null|undefined;

    /**
     * Removes references to the CodeMirror editor.
     * It removes event listeners and removes the editor from local DOM.
     */
    removeCodeMirror(): void;

    /**
     * Updates model data on the `code-mirror` element.
     *
     * @param model New model
     */
    _updateCmModel(model: any[]|null): void;

    /**
     * Updates Code Mirror editor `narrow` property.
     *
     * @param narrow New value
     */
    _updateCmNarrow(narrow: Boolean|null): void;

    /**
     * Updates the value when form data editor's value change
     */
    _formValueChanged(e: any): void;

    /**
     * Updates the value when CodeMirror editor's value change
     */
    _cmValueChanged(e: any): void;

    /**
     * Handler for `viewModel` change.
     * Updates currently opened editor.
     *
     * @param model New model
     */
    _viewModelChanged(model: any[]|null): void;

    /**
     * Handler for `narrow` change.
     * Updates currently opened editor.
     *
     * @param narrow New value
     */
    _narrowChanged(narrow: Boolean|null): void;

    /**
     * Updates `disallowCustom` on form editor.
     *
     * @param state New state of property
     */
    _disallowCustomChanged(state: Boolean|null): void;

    /**
     * Creates a headers string from a model.
     *
     * @param model Optional, model to process. If not set it uses
     * `this.viewModel`
     * @returns Generated headers
     */
    modelToValue(model: any[]|null): String|null;

    /**
     * Code mirror's ctrl+space key handler.
     * Opens headers fill support.
     *
     * @param cm Code mirror instance.
     */
    _cmKeysHandler(cm: object|null): void;

    /**
     * Handler for `sourceMode` change.
     *
     * Opens desired editr.
     */
    _sourceModeChanged(isSource: Boolean|null): void;

    /**
     * Called when switching from source view to form view.
     * Updates view model with values defined in text editor.
     *
     * Only headers existing in `value` are going to be present in the model.
     * Otherwise headers will be disabled.
     *
     * It does nothing if `value` or `viewModel` is not defined.
     */
    _modelFromValue(): void;

    /**
     * Finds item position in model by name.
     *
     * @param model Model items
     * @param name Header name to search for
     * @returns Items position or `-1` if not found.
     */
    _findModelIndex(model: any[]|null, name: String|null): Number|null;

    /**
     * Creates a custom header model item.
     *
     * @param defaults Default data
     * @returns View model item
     */
    createCustom(defaults: object|null): object|null;

    /**
     * Handler tor the `request-headers-changed` event.
     * Updates the editor value to the value of the event detail object.
     */
    _headersChangedHandler(e: any): void;

    /**
     * Handler for the `request-header-changed` event.
     * It updates value for a single header.
     */
    _headerChangedHandler(e: any): any;

    /**
     * Detects and sets content type value from changed headers value.
     *
     * @param value Headers new value.
     */
    _detectContentType(value: String|null): void;

    /**
     * Called by CodeMirror editor.
     * When something change n the headers list, detect content type header.
     */
    _valueChanged(value: any): void;
    _onContentTypeChanged(currentCt: any): void;
    _notifyContentType(type: any): void;
    _setValues(value: any): void;

    /**
     * Coppies current response text value to clipboard.
     */
    _copyToClipboard(): void;
    _resetCopyButtonState(button: any): void;
  }
}

interface HTMLElementTagNameMap {
  "api-headers-editor": ApiElements.ApiHeadersEditor;
}
